### ISSUE TITLE
run.sh -c doesn't work but change pipex-tester/script/config.sh then work fine

### ISSUE THREAD

**Issue by exgs** [vfurmane/pipex-tester#1]
https://github.com/vfurmane/pipex-tester/blob/38cc9697aa86c8321deeadd85af25a1c4cca3b5d/scripts/config.sh#L22

I'm using MacOs BigSur & Mac Air 2020. 
when `run.sh -c`doesn't work for my cadets. 
like as. 
<img width="1033" alt="스크린샷 2021-07-16 오후 7 18 25" src="https://user-images.githubusercontent.com/56223639/125932985-e9d88df8-22ff-416a-b2f7-7ec013cea417.png">

So, just Change`read -N 1 -r check_update` TO `read -n 1 -r check_update` then work fine

**Comment by vfurmane** [comment]
Hello, thanks for your feedback.

The main problem, as you probably noticed, is that `bash` does not behave the same way on Linux and on Darwin. So using `-n` globally would have other drawbacks on Linux. So I just used an `if` statement to check the `OSTYPE`, and the script will select the right option.

You can `git pull` and everything should work as expected. Let me know if it is not the case ! 🙂

**Comment by exgs** [comment]
No more appear! Thanks for your working.
