### ISSUE TITLE
Need help with the test 14.

### ISSUE THREAD

**Issue by anderamo** [vfurmane/pipex-tester#3]
Hi im trying to check the 14th test: The program uses the environment list. Can you help me with that? Thanks.

**Comment by vfurmane** [comment]
Hi @anderamo,

unfortunately, I can't help you much without any further details. You can write the logs presents in the `outs` folder (`outs/test-14*.txt`). Explain your problem and give as much details as you can. As every programmer will respond this to you, I am forced to do so: see https://dontasktoask.com. 😉 

Moreover, this is not the right place to ask that kind of questions. Here, you can share some bug you found, a documentation mistake, a test that would fit in the tester, etc... But for help about your project, you should ask me on Slack or eventually Discord (if you are from Paris campus, you can easily find me). You can even ask in a general channel, some nice guy will help you for sure.

I am then waiting you in private messages on Slack for you to give me more informations to help you properly. See you soon !
