### ISSUE TITLE
Test 1 & 2 failed

### ISSUE THREAD

**Issue by OSS-42** [vfurmane/pipex-tester#9]
**Describe the bug**
In my case, I see 'KO' for tests `#1` & `#2`, when in my terminal I don't have any problem compiling.

**Expected behavior**
Tests 1 & 2 being OK

**Desktop (please complete the following information):**
 - OS: Windows 11 + WSL2

![pipex-tests-KO](https://user-images.githubusercontent.com/26226380/196257773-bc6fdf02-102f-477b-aa56-2640c0d15403.png)
![pipex-tests-KO-make](https://user-images.githubusercontent.com/26226380/196258093-089b2c5a-400f-4753-a95e-1ad02c99003d.png)
![pipex-tests-KO-outs](https://user-images.githubusercontent.com/26226380/196257794-9eb744df-822f-42fe-909d-5cdf8b330f9d.png)

edit : replaced text with latest picture.

**Comment by vfurmane** [comment]
Hello,

it seems that the directory `../42-pipex` does not exist from the tester point of view. Can you confirm you file hierarchy is as follow:

```
42Quebec/
├── 42-pipex/
└── pipex-tester/
```

**Comment by OSS-42** [comment]
Hello, no, the folder structure is not like that, as I got cloned pipex-tester from 42-pipex.
So the structure is :
42Quebec>42-pipex(where my pipex is)>pipex-tester

Should I got clone on 42Quebec instead ?

**Comment by OSS-42** [comment]
OK, I misread 'alongside pipex directory". All good. My mistake. sorry.
